# MongoDB StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: cookbook
  labels:
    app: mongodb
spec:
  serviceName: mongodb-service
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        ports:
        - containerPort: 27017
          name: mongodb
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-database
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        - name: mongo-config
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - db.adminCommand('ping')
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - db.adminCommand('ping')
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: mongo-config
        configMap:
          name: mongo-init-script
          defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi

---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: cookbook
  labels:
    app: mongodb
spec:
  clusterIP: None
  ports:
  - port: 27017
    name: mongodb
  selector:
    app: mongodb

---
# ConfigMap for MongoDB initialization script
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
  namespace: cookbook
  labels:
    app: mongodb
data:
  init-db.js: |
    db.getSiblingDB(process.env.MONGO_INITDB_DATABASE || 'cookbook').createUser({
      user: process.env.MONGO_INITDB_ROOT_USERNAME || 'cookbook-user',
      pwd: process.env.MONGO_INITDB_ROOT_PASSWORD || 'cookbookuserpass',
      roles: [{ role: 'readWrite', db: process.env.MONGO_INITDB_DATABASE || 'cookbook' }]
    });
